AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  HelloTuring

  Sample SAM Template for HelloTuring

Globals:
  Function:
    Timeout: 3

Resources:
  HelloTuringFunction:
    Type: AWS::Lambda::Function
    Properties:
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        ApiKeyRequired: false # sets for all methods
      Cors:
        AllowCredentials: false
        AllowHeaders: '"Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token"'
        AllowMethods: '"POST,GET,OPTION"'
        AllowOrigin: '"*"'
      CodeUri: hello_turing/
      Handler: app.lambda_handler # needs to match file and function name
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HttpGet:
          Type: Api
          Properties:
            Auth:
              AddDefaultAuthorizerToCorsPreflight: false
              ApiKeyRequired: false # sets for all methods
            Cors:
              AllowCredentials: false
              AllowHeaders: '"Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token"'
              AllowMethods: '"POST,GET,OPTION"'
              AllowOrigin: '"*"'
            Path: /hello # overall URL must not be longer than 64 bytes, '/' recommended
            Method: get
        # KeepWarm: # Optional
        #   Type: Schedule
        #   Properties:
        #     Schedule: 'rate(5 minutes)'
        #     Name: KeepWarmSchedule
        #     Description: Used to keep the Lambda warm
        #     Enabled: true





#             AWSTemplateFormatVersion: '2010-09-09'
# Transform: AWS::Serverless-2016-10-31
# Description: >
#   HelloTuring

#   Sample SAM Template for HelloTuring

# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# Globals:
#   Function:
#     Timeout: 3

# Resources:
#   HelloWorldFunction:
#     Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#     Properties:
#       CodeUri: hello_world/
#       Handler: app.lambda_handler
#       Runtime: python3.9
#       Architectures:
#         - x86_64
#       Events:
#         HelloWorld:
#           Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#           Properties:
#             Path: /hello
#             Method: get

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn